### PR TITLE
scale predict box back to image space

### PR DESCRIPTION
**Pull request by pure-water**
Scale predict box back to image space

### CODE REVIEW

**Comment by pure-water** [comment]
Scale predict box back to image space

**Comment by pure-water** [comment]
scale predict box back to image space

**Comment by sroj** [comment]
Hi. Getting this error on this PR:

```
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    _main_(args)
  File "train.py", line 100, in _main_
    debug              = config['train']['debug'])
  File "/h/285/srojas/mlcv_proj/keras-yolo2/frontend.py", line 341, in train
    average_precisions = self.evaluate(valid_generator)
  File "/h/285/srojas/mlcv_proj/keras-yolo2/frontend.py", line 373, in evaluate
    raw_height, raw_width, raw_channels = raw_img.shape
NameError: global name 'raw_img' is not defined
```

**Comment by pure-water** [comment]
typo fixed. Try again

**Pull request merged**
